[package]
    name = "cordy"
    version = "0.1.0"
    edition = "2018"

[dependencies]
    lazy_static = "1.4.0"
    hashlink = "0.8.1"
    rustyline = "10.0.0"
    num-integer = "0.1.45"
    itertools = "0.10.5"

#[profile.release]
#    debug = true